# Generated by Django 5.1 on 2024-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='vauthor',
            new_name='author',
        ),
    ]
