# Generated by Django 5.1 on 2024-09-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_logintable_userproile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logintable',
        ),
        migrations.DeleteModel(
            name='Userproile',
        ),
    ]
