# Generated by Django 5.0.3 on 2024-09-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acccounts', '0002_rename_userproile_userprofile'),
        ('formapp', '0006_book_quantity'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='formapp.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acccounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bookh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.book')),
                ('carth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='book',
        ),
    ]
